version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: buster
        CARGO_HOME: /workspace/.cargo

    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:qbittorrent

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  qbittorrent:
    image: linuxserver/qbittorrent:4.4.3
    restart: unless-stopped
