on:
  - push
jobs:
  check:
    name: Rust project
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
  