name: Extra
on:
  push:
    branches:
      - main
jobs:
  extra:
    runs-on: ubuntu-22.04
    steps:
      # build and cache this here in order to reuse it's cache in feature branches
      - name: Install cargo-edit
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-edit
          version: 0.9.1