on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Login
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: --token ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish qbittorrent-web-api-gen
        uses: actions-rs/cargo@v1
        with:
          command: publish

      # - name: Publish qbittorrent-web-api
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: publish
  