on:
  push:
    branches:
      - 'main' 
jobs:
  tag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          version: "$(cat Cargo.toml | grep version | head -1 | sed 's/version = //' | sed 's/"//g')"
          tag_prefix: "v"